### ISSUE TITLE
z-index issue

### ISSUE THREAD

**Issue by fikrifirat** [voxbone-workshop/click2vox-com#680]
Happens on https://www.voxbone.com/register

The issue can easily be replicated by adding this CSS through the browser console on the `<footer>` tag. After adding these, you won't be able to edit the form.
```
position: relative;
z-index: 100;
```

We had an issue yesterday with a the C2C widget on the registration page. The button is working fine, but it's adding an element to the page that conflicts with the styling on the registration page.

The registration page is a bit different from everything else on the website. The footer on this page needs to stay on top, because the sidebar needs to stay fixed on the page and still scroll under the footer.

The footer had a z-index of "100", and as the C2C widget is included in the footer, the div "vox-widget-draggable" was on top of everything on the page. (Even though it was set to a z-index "-1". The z-index is always measured relative from it's parent element.)

As a temporary fix, I removed the fixed position of the sidebar, and removed the z-index from the footer.

@ashostak for review

**Comment by san983** [comment]
@fikrifirat This is the one you mentioned in the email today, right?

**Comment by chadwallacehart** [comment]
@fikrifirat - did this happen as a result of a change to voxbone.com/register or was it because of changes on our side?

**Comment by agonza1** [comment]
I believe it is due to the changes we made or may be a change in voxbone.com/register too. But definitively the problem is a combination of the draggability container and the change/"inheritance" of the button parent z-index and position:relative at the same time. For containing the widget we are displaying a container with no z...but when the z of the widget parent changes and is higher than other elements in the page we will be covering those elements with the container. 
I was working on it yesterday but I couldn't figure out a fast solution so I will be speaking with Santi later

**Comment by fikrifirat** [comment]
@agonza1 This also happens on customer website. `draggable` div prevents any clicks to the header bar (i.e. sign in/register buttons)
https://virtualglobalphone.com/

**Comment by agonza1** [comment]
Update:

Finally we will be defaulting draggabilly to false and using `data-draggable="true"` to enable draggabilly.
This is done in order to avoid some of the problems faced when you change the z-index in the widget or some of its parent elements.

This won't be visually available in the click2vox site but a customer could add this feature manually.

**Comment by san983** [comment]
So, are we ok that all the existing widgets/buttons won't have this feature enabled unless they manually add  `data-draggable="true"`?

**Comment by agonza1** [comment]
I think so, we can do this or provide always the draggable option but avoid adding any kind of container option. The drawback of the second option is that the user might be able to move the widget outside the screen.
Both options are OK to me but none of them is perfect.
