### ISSUE TITLE
Click2Vox SDK

### ISSUE THREAD

**Issue by fikrifirat** [voxbone-workshop/click2vox-com#695]
It would deliver a better experience for developers and custom implementations of web calling if we  encapsulated methods and events related to Click2Vox for people who just need the calling but not the button or its generator.

**Comment by agonza1** [comment]
Current followed approach:
**1) click2vox.js script loaded through an anonymous function:**
E.g.: 
`(function(window, document) {
  var loader = function() {
    var script = document.createElement("script"),
      tag = document.getElementsByTagName("script")[0];
  script.src="https://click2vox/click2vox.js?buttonid=58a1ce63ea9a984006ae68c6";
    script.async = 1;
    tag.parentNode.insertBefore(script, tag);
  };`

This will load click2vox but won't be enough to initiate a call, we need the configuration parameters, at least a DID. 
We are adding an optional `buttonid` parameter to be passed to click2vox. This button_id is used when posting the ratings to the local DB only. In case of not having it everything will work (it is only needed if a customer is using more than one button in one page and he wants to differentiate between them).

**2) Passing the configuration parameters as a JSON**
E.g:`var click2vox = { text: "call", did: "883510080361", send_digits: "#11", incompatible_browser_configuration: "hide_widget", server_url: "http://localhost:3000", use_default_button_css: "true", div_css_class_name: "style-b", show_frame: "true", show_branding: "false", test_setup:"false", draggable:"true"}`

**3) Customizable global variable**
Proposed by @fikrifirat. Potential solution suggested by @san983 here: https://github.com/voxbone-workshop/click2vox-com/issues/696 (TBC)

**4)Exposing functions through the click2vox variable**
Currently: `click2vox.makeCall()`,`click2vox.handUp()`,`click2vox.destroyWidget()`, maybe others...

**5) For multiple buttons/widgets:**
`var click2vox = [{did: "883510080361"},{ text: "call", did: "883510080361", send_digits: "#11", incompatible_browser_configuration: "hide_widget", server_url: "http://localhost:3000"}]` (TODO)

Example: https://jsfiddle.net/agonza1/9toeej5q/3/

Other options/ Additional interesting features:
- Exposing events
- Adding a object constructor in click2vox that allows the customer to add the configuration parameters with or without `""`

**Comment by agonza1** [comment]
After Merging to master we left few interesting features:
- Multiple buttons/widgets:**
`var click2vox = [{did: "883510080361"},{ text: "call", did: "883510080361", send_digits: "#11", incompatible_browser_configuration: "hide_widget", server_url: "http://localhost:3000"}]` 
- Exposing call events #699 
- Adding a object constructor in click2vox that allows the customer to add the configuration parameters with or without `""`

Aside from that we build the other functionalities into #711 

Summary:
If there is a <div> that use a voxButton class in the document we will load the old working button. Otherwise we will load the floating button. For loading this button we will need to declare its configuration with the following initializer:
`var click2vox = {
  //display_button: "false",
  custom_button_color: "#ec1515",
  did: "883510080361",
  send_digits: "#11",
  incompatible_browser_configuration: "hide_widget",
  server_url: "https://development.click2vox.com",
  use_default_button_css: "true",
  div_css_class_name: "btn-style-round-a",
  placement: "bottom-right",
  draggable: "true"
}`
With all its parameters keeping the same naming convention used for the <div> data tags.
And regarding exposed functions we have:
- makeCall(boolean) where Boolean if it is false won't display the widget
- handUp() will hangup the call
- destroyWidget() will delete the call widget

Working example: https://jsfiddle.net/agonza1/bLkykex1/2/
